blank_issues_enabled: true
contact_links:
  - name: Quantum Coin Core Security Policy
    url: https://github.com/qtc/qtc/blob/master/SECURITY.md
    about: View security policy
  - name: Quantum Coin Core Developers
    url: https://qtccore.org
    about: Quantum Coin Core homepage
